// anothergame - ReXGlue Recompiled Project
// Generated by: rexglue init
//
// This file is SDK-managed. Customizations go in virtual hook overrides.
// Running 'rexglue migrate' will overwrite this file.

#include "generated/anothergame_config.h"
#include "generated/anothergame_init.h"

#include <rex/rex_app.h>
#include <rex/ppc/function.h>


class AnothergameApp : public rex::ReXApp {
 public:
  using rex::ReXApp::ReXApp;

  static std::unique_ptr<rex::ui::WindowedApp> Create(
      rex::ui::WindowedAppContext& ctx) {
    return std::unique_ptr<AnothergameApp>(new AnothergameApp(ctx, "anothergame",
        {PPC_CODE_BASE, PPC_CODE_SIZE, PPC_IMAGE_BASE,
         PPC_IMAGE_SIZE, PPCFuncMappings}));
  }
};

REX_DEFINE_APP(anothergame, AnothergameApp::Create)

    PPC_STUB(__imp__ExAllocatePoolWithTag);
    PPC_STUB(__imp__XUsbcamSetView);
    PPC_STUB(__imp__XUsbcamSetConfig);
    PPC_STUB(__imp__XUsbcamSetCaptureMode);
    PPC_STUB(__imp__XUsbcamReadFrame);
    PPC_STUB(__imp__XUsbcamGetState);
    PPC_STUB(__imp__XUsbcamDestroy);
    PPC_STUB(__imp__XUsbcamCreate);
    PPC_STUB(__imp__XamVoiceSubmitPacket);
    PPC_STUB(__imp__XamUserCreateStatsEnumerator);
    PPC_STUB(__imp__XamShowPlayerReviewUI);
    PPC_STUB(__imp__XamShowMarketplaceUI);
    PPC_STUB(__imp__XamShowGamerCardUIForXUID);
    PPC_STUB(__imp__XamShowAchievementsUI);
    PPC_STUB(__imp__ObReferenceObject);
    PPC_STUB(__imp__NetDll_XNetUnregisterInAddr);
    PPC_STUB(__imp__NetDll_XNetQosLookup);
    PPC_STUB(__imp__NetDll_XNetGetConnectStatus);
